typography_spectrum: 0.8728020961862057
content_rating:
  adult: false
color:
  brandStrength: 0.5158841330558062
  lightness: 0.36072094133123755
  saturation: 0.8833881900645792
  rhythmicContrast: 0.3878971349913627
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
layout_spectrum: 0.5732014589011669
author:
  name: Daniel Fox
  email: danieljamesfox@yahoo.ca
  url: 'http://www.danielfoxofficial.com/'
name: Daniel Fox
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5d834a7d-00e8-4153-b070-740689182a41.ico
title: DanielFoxOfficial.com
description: Wherein We Learn to Write Better
