typography_spectrum: 0.6661154807079583
content_rating:
  adult: false
color:
  brandStrength: 0.9731372082605958
  lightness: 0.7040277924388647
  saturation: 0.8433099507819861
  rhythmicContrast: 0.027827132027596235
  brandColors:
    - '#000000'
    - '#AF922E'
    - '#761816'
    - '#E7C13C'
    - '#8F5F22'
layout_spectrum: 0.220720344921574
author:
  name: Daniel Fox
  email: danieljamesfox@yahoo.ca
  url: 'http://www.danielfoxofficial.com/'
name: Daniel Fox
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5d834a7d-00e8-4153-b070-740689182a41.ico
title: DanielFoxOfficial.com
description: Wherein We Learn to Write Better
