typography_spectrum: 0.13586251414380968
content_rating:
  adult: false
color:
  brandStrength: 0.4937425749376416
  lightness: 0.9647164260968566
  saturation: 0.7925890169572085
  rhythmicContrast: 0.6140595702454448
  brandColors:
    - '#000000'
    - '#AF922E'
    - '#761816'
    - '#E7C13C'
    - '#8F5F22'
layout_spectrum: 0.49535890645347536
author:
  name: Daniel Fox
  email: danieljamesfox@yahoo.ca
  url: 'http://www.danielfoxofficial.com/'
name: Daniel Fox
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5d834a7d-00e8-4153-b070-740689182a41.ico
title: DanielFoxOfficial.com
description: Wherein We Learn to Write Better
