typography_spectrum: 0.1634478874038905
content_rating:
  adult: false
color:
  brandStrength: 0.9736212971620262
  lightness: 0.3486732810270041
  saturation: 0.6676986869424582
  rhythmicContrast: 0.6203992974478751
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
layout_spectrum: 0.4853542784694582
author:
  name: Daniel Fox
  email: danieljamesfox@yahoo.ca
  url: 'http://www.danielfoxofficial.com/'
name: Daniel Fox
navigation:
  - name: Blog
    url: 'http://www.danielfoxofficial.com/danielfoxblog'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5d834a7d-00e8-4153-b070-740689182a41.ico
title: DanielFoxOfficial.com
description: Wherein We Learn to Write Better
